easy_admin:
    entities:
        Category:
            class: App\Entity\Category
            label: 'Categories'
            list:
                actions:
                    - { name: 'show', icon: 'search', label: false, title: 'Show' }
                    - { name: 'edit', icon: 'pencil', label: false, title: 'Edit' }
                    - { name: 'delete', icon: 'remove', label: false, title: 'Delete' }
                fields:
                    - 'id'
                    - { property: 'name', label: 'Label' }
                    - 'products'
            show:
                fields:
                    - 'id'
                    - { property: 'name', label: 'Label', css_class: 'large' }
                    - 'products'
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-12' }
                    -   property: translations
                        type: 'A2lix\TranslationFormBundle\Form\Type\TranslationsType'
                        type_options:
                            label: false
                            excluded_fields: ['slug']
                    # if you want to add products when creating categories, add the 'by_reference' option
                    # - { property: 'products', type_options: { by_reference: false } }
